spring:
  application:
    name: customer
  profiles:
    active: production
  datasource:
    url: jdbc:mysql://localhost:3306/creditinfo?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: creditinfo
    password: creditinfo
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update

eureka:
  client: ${eureka-client}

eureka-client:
  fetchRegistry: true